# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

puts "Seeding Data..."

# -------------------------------------------------------------------
# 
puts "Starting Manufacturer Data..."
# Manufacturer.create(name: "", abbreviation: "")
Manufacturer.create(name: "Alaska Bullet Company", abbreviation: "AK")
Manufacturer.create(name: "Barnes", abbreviation: "BAR")
Manufacturer.create(name: "Berger", abbreviation: "BRGR")
Manufacturer.create(name: "Berry's", abbreviation: "BRY")
Manufacturer.create(name: "Cast Performance", abbreviation: "CP")
Manufacturer.create(name: "Federal", abbreviation: "FD")
Manufacturer.create(name: "GS Custom Bullets", abbreviation: "GS")
Manufacturer.create(name: "Hornady", abbreviation: "HDY")
Manufacturer.create(name: "Hawk", abbreviation: "HWK")
Manufacturer.create(name: "Laser Cast", abbreviation: "LC")
Manufacturer.create(name: "Lyman", abbreviation: "LYM")
Manufacturer.create(name: "Montana Cast Bullets", abbreviation: "MCB")
Manufacturer.create(name: "Mount Baldy", abbreviation: "MTB")
Manufacturer.create(name: "Montana Gold", abbreviation: "MTG")
Manufacturer.create(name: "Nosler", abbreviation: "NOS")
Manufacturer.create(name: "Oregon Trail", abbreviation: "OT")
Manufacturer.create(name: "Rainier", abbreviation: "RAN")
Manufacturer.create(name: "Remington", abbreviation: "REM")
Manufacturer.create(name: "Rushmore", abbreviation: "RSH")
Manufacturer.create(name: "Sierra", abbreviation: "SIE")
Manufacturer.create(name: "SinterFire", abbreviation: "SF")
Manufacturer.create(name: "Speer", abbreviation: "SPR")
Manufacturer.create(name: "True Shoot", abbreviation: "TS")
Manufacturer.create(name: "West Coast", abbreviation: "WC")
Manufacturer.create(name: "Woodleigh", abbreviation: "WDL")
Manufacturer.create(name: "Winchester", abbreviation: "WIN")
puts "Finished Manufacturer data"

# -------------------------------------------------------------------
puts "Starting LoadType data..."
@pistol = LoadType.create(name: "Pistol")
@rifle = LoadType.create(name: "Rifle")
puts "Finished LoadType data"



# -------------------------------------------------------------------
puts "Starting Caliber data..."
puts "... pistol data ..."
Caliber.create(name: "17 Bumble Bee", load_type: @pistol)
Caliber.create(name: "22 Remington Jet", load_type: @pistol)
Caliber.create(name: "22 Hornet", load_type: @pistol)
Caliber.create(name: "22 K Hornet", load_type: @pistol)
Caliber.create(name: "221 Fireball", load_type: @pistol)
Caliber.create(name: "222 Remington", load_type: @pistol)
Caliber.create(name: "223 Remington", load_type: @pistol)
Caliber.create(name: "22 BR Remington", load_type: @pistol)
Caliber.create(name: "6mm TCU", load_type: @pistol)
Caliber.create(name: "6mm-204 RR", load_type: @pistol)
Caliber.create(name: "6mm BR Remington", load_type: @pistol)
Caliber.create(name: "243 Winchester", load_type: @pistol)
Caliber.create(name: "25 ACP", load_type: @pistol)
Caliber.create(name: "25-35 Winchester", load_type: @pistol)
Caliber.create(name: "256 Winchester", load_type: @pistol)
Caliber.create(name: "6.5mm TCU", load_type: @pistol)
Caliber.create(name: "6.5mm BR", load_type: @pistol)
Caliber.create(name: "6.5mm JDJ", load_type: @pistol)
Caliber.create(name: "270 Ren", load_type: @pistol)
Caliber.create(name: "270 Winchester", load_type: @pistol)
Caliber.create(name: "7mm TCU", load_type: @pistol)
Caliber.create(name: "7mm BR Remington", load_type: @pistol)
Caliber.create(name: "7-30 Waters", load_type: @pistol)
Caliber.create(name: "7mm IHMSA", load_type: @pistol)
Caliber.create(name: "7mm-08 Remington", load_type: @pistol)
Caliber.create(name: "30 Luger (7.65mm Parabellum)", load_type: @pistol)
Caliber.create(name: "30 Carbine", load_type: @pistol)
Caliber.create(name: "30 Herrett", load_type: @pistol)
Caliber.create(name: "30-30 Winchester", load_type: @pistol)
Caliber.create(name: "308 Winchester", load_type: @pistol)
Caliber.create(name: "30-06", load_type: @pistol)
Caliber.create(name: "32 ACP", load_type: @pistol)
Caliber.create(name: "32 S&W", load_type: @pistol)
Caliber.create(name: "32 S&W Long", load_type: @pistol)
Caliber.create(name: "32 North American Arms", load_type: @pistol)
Caliber.create(name: "32 H&R Magnum", load_type: @pistol)
Caliber.create(name: "32-20 Winchester", load_type: @pistol)
Caliber.create(name: "327 Federal Magnum", load_type: @pistol)
Caliber.create(name: "380 Auto", load_type: @pistol)
Caliber.create(name: "38 S&W", load_type: @pistol)
Caliber.create(name: "38 Short Colt", load_type: @pistol)
Caliber.create(name: "38 Long Colt", load_type: @pistol)
Caliber.create(name: "9mm Luger", load_type: @pistol)
Caliber.create(name: "38 Super Auto", load_type: @pistol)
Caliber.create(name: "38 Super Auto +P", load_type: @pistol)
Caliber.create(name: "9x23 mm Winchester", load_type: @pistol)
Caliber.create(name: "38 Special", load_type: @pistol)
Caliber.create(name: "38 Special +P", load_type: @pistol)
Caliber.create(name: "357 SIG", load_type: @pistol)
Caliber.create(name: "357 Magnum", load_type: @pistol)
Caliber.create(name: "357-44 Bain & Davis", load_type: @pistol)
Caliber.create(name: "357 Remington Maximum", load_type: @pistol)
Caliber.create(name: "357 Herrett", load_type: @pistol)
Caliber.create(name: "35 Remington", load_type: @pistol)
Caliber.create(name: "9 x 18mm Makarov", load_type: @pistol)
Caliber.create(name: "375 Super Mag", load_type: @pistol)
Caliber.create(name: "375 JDJ", load_type: @pistol)
Caliber.create(name: "38-40 Winchester", load_type: @pistol)
Caliber.create(name: "40 S&W", load_type: @pistol)
Caliber.create(name: "10mm Auto", load_type: @pistol)
Caliber.create(name: "41 Action Express", load_type: @pistol)
Caliber.create(name: "41 Remington Magnum", load_type: @pistol)
Caliber.create(name: "44 Colt", load_type: @pistol)
Caliber.create(name: "44 Russian", load_type: @pistol)
Caliber.create(name: "44 S&W Special", load_type: @pistol)
Caliber.create(name: "44-40 Winchester", load_type: @pistol)
Caliber.create(name: "44 Remington Magnum", load_type: @pistol)
Caliber.create(name: "44 Auto Mag", load_type: @pistol)
Caliber.create(name: "445 Super Mag", load_type: @pistol)
Caliber.create(name: "444 Marlin", load_type: @pistol)
Caliber.create(name: "45 S&W (Schofield)", load_type: @pistol)
Caliber.create(name: "45 GAP (Glock Auto)", load_type: @pistol)
Caliber.create(name: "45 ACP", load_type: @pistol)
Caliber.create(name: "45 SUPER", load_type: @pistol)
Caliber.create(name: "460 Rowland", load_type: @pistol)
Caliber.create(name: "45 Colt", load_type: @pistol)
Caliber.create(name: "45 Colt (Ruger, Freedom Arms & T/C only)", load_type: @pistol)
Caliber.create(name: "45 Winchester Magnum", load_type: @pistol)
Caliber.create(name: "450 Extreme", load_type: @pistol)
Caliber.create(name: "454 Casull", load_type: @pistol)
Caliber.create(name: "460 S&W MAGNUM", load_type: @pistol)
Caliber.create(name: "45-70 Government", load_type: @pistol)
Caliber.create(name: "480 Ruger", load_type: @pistol)
Caliber.create(name: "475 Linebaugh", load_type: @pistol)
Caliber.create(name: "50 Action Express", load_type: @pistol)
Caliber.create(name: "500 Linebaugh", load_type: @pistol)
Caliber.create(name: "500 Wyoming Express", load_type: @pistol)
Caliber.create(name: "500 S&W Magnum", load_type: @pistol)
puts "... loading rifle data ..."
Caliber.create(name: "17 Ackley Hornet", load_type: @rifle)
Caliber.create(name: "17 Ackley Bee", load_type: @rifle)
Caliber.create(name: "17 Mach IV", load_type: @rifle)
Caliber.create(name: "17 Remington Fireball", load_type: @rifle)
Caliber.create(name: "17-222", load_type: @rifle)
Caliber.create(name: "17-223", load_type: @rifle)
Caliber.create(name: "17 Remington", load_type: @rifle)
Caliber.create(name: "20 Tactical", load_type: @rifle)
Caliber.create(name: "204 Ruger", load_type: @rifle)
Caliber.create(name: "22 Hornet", load_type: @rifle)
Caliber.create(name: "22 K Hornet", load_type: @rifle)
Caliber.create(name: "218 Bee", load_type: @rifle)
Caliber.create(name: "221 Fireball", load_type: @rifle)
Caliber.create(name: "222 Remington", load_type: @rifle)
Caliber.create(name: "223 Remington", load_type: @rifle)
Caliber.create(name: "222 Remington Magnum", load_type: @rifle)
Caliber.create(name: "22 PPC", load_type: @rifle)
Caliber.create(name: "22 BR Remington", load_type: @rifle)
Caliber.create(name: "224 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "219 Wasp", load_type: @rifle)
Caliber.create(name: "225 Winchester", load_type: @rifle)
Caliber.create(name: "22-250 Remington", load_type: @rifle)
Caliber.create(name: "220 Swift", load_type: @rifle)
Caliber.create(name: "220 Jaybird", load_type: @rifle)
Caliber.create(name: "22 CHeetah Mark II", load_type: @rifle)
Caliber.create(name: "223 Winchester Super Short Magnum", load_type: @rifle)
Caliber.create(name: "6mm-222", load_type: @rifle)
Caliber.create(name: "6 x 45mm (6mm-223)", load_type: @rifle)
Caliber.create(name: "6 x 47mm", load_type: @rifle)
Caliber.create(name: "6mm PPC", load_type: @rifle)
Caliber.create(name: "6mm BR Remington", load_type: @rifle)
Caliber.create(name: "6mm-250", load_type: @rifle)
Caliber.create(name: "243 Winchester", load_type: @rifle)
Caliber.create(name: "6mm Remington", load_type: @rifle)
Caliber.create(name: "243 Winchester Super Short Magnum", load_type: @rifle)
Caliber.create(name: "6mm - 284", load_type: @rifle)
Caliber.create(name: "240 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "25-20 Winchester", load_type: @rifle)
Caliber.create(name: "256 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "25-35 Winchester", load_type: @rifle)
Caliber.create(name: "257 Kimber", load_type: @rifle)
Caliber.create(name: "250-3000 Savage", load_type: @rifle)
Caliber.create(name: "257 Roberts", load_type: @rifle)
Caliber.create(name: "25-284", load_type: @rifle)
Caliber.create(name: "25-06 Remington", load_type: @rifle)
Caliber.create(name: "25 Winchester Super Short Magnum", load_type: @rifle)
Caliber.create(name: "257 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "6.5mm Grendel", load_type: @rifle)
Caliber.create(name: "6.5mm BR", load_type: @rifle)
Caliber.create(name: "6.5 x 50mm Japanese", load_type: @rifle)
Caliber.create(name: "6.5mm Carcano", load_type: @rifle)
Caliber.create(name: "6.5 Creedmoor", load_type: @rifle)
Caliber.create(name: "260 Remington", load_type: @rifle)
Caliber.create(name: "6.5 x 55mm Swedish Mauser", load_type: @rifle)
Caliber.create(name: "6.5mm-06", load_type: @rifle)
Caliber.create(name: "6.5-284", load_type: @rifle)
Caliber.create(name: "6.5mm Remington Magnum", load_type: @rifle)
Caliber.create(name: "264 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "6.8 mm Remington SPC", load_type: @rifle)
Caliber.create(name: "270 Winchester", load_type: @rifle)
Caliber.create(name: "270 Winchester Short Magnum", load_type: @rifle)
Caliber.create(name: "270 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "7mm BR Remington", load_type: @rifle)
Caliber.create(name: "7-30 Waters", load_type: @rifle)
Caliber.create(name: "7mm-08 Remington", load_type: @rifle)
Caliber.create(name: "7mm Shooting Times Easterner", load_type: @rifle)
Caliber.create(name: "7 x 57mm Mauser", load_type: @rifle)
Caliber.create(name: "280 Remington", load_type: @rifle)
Caliber.create(name: "284 Winchester", load_type: @rifle)
Caliber.create(name: "280 Ackley Improved", load_type: @rifle)
Caliber.create(name: "7mm Rem. S.A. Ultra Mag.", load_type: @rifle)
Caliber.create(name: "7mm Winchester Short Magnum", load_type: @rifle)
Caliber.create(name: "7mm Remington Magnum", load_type: @rifle)
Caliber.create(name: "7mm Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "7mm Shooting Times Westerner", load_type: @rifle)
Caliber.create(name: "7mm Remington Ultra Magnum", load_type: @rifle)
Caliber.create(name: "30 Carbine", load_type: @rifle)
Caliber.create(name: "300 AAC Blackout", load_type: @rifle)
Caliber.create(name: "30-30 Winchester", load_type: @rifle)
Caliber.create(name: "30 AR Remington", load_type: @rifle)
Caliber.create(name: "30-40 Krag", load_type: @rifle)
Caliber.create(name: "7.5 x 55mm Swiss", load_type: @rifle)
Caliber.create(name: "300 Savage", load_type: @rifle)
Caliber.create(name: "7.62 x 54R", load_type: @rifle)
Caliber.create(name: "30 Remington", load_type: @rifle)
Caliber.create(name: "307 Winchester", load_type: @rifle)
Caliber.create(name: "308 Marlin Express", load_type: @rifle)
Caliber.create(name: "30 TC", load_type: @rifle)
Caliber.create(name: "308 Winchester", load_type: @rifle)
Caliber.create(name: "30-06", load_type: @rifle)
Caliber.create(name: "300 H & H Magnum", load_type: @rifle)
Caliber.create(name: "308 Norma Magnum", load_type: @rifle)
Caliber.create(name: "300 Ruger Compact Magnum", load_type: @rifle)
Caliber.create(name: "300 Remington S.A. Ultra Mag.", load_type: @rifle)
Caliber.create(name: "300 Winchester Short Magnum", load_type: @rifle)
Caliber.create(name: "300 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "300 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "300 Remington Ultra Mag", load_type: @rifle)
Caliber.create(name: "30-378 Weatherby", load_type: @rifle)
Caliber.create(name: "7.62 x 39mm Russian", load_type: @rifle)
Caliber.create(name: "303 Savage", load_type: @rifle)
Caliber.create(name: "7.7 x 58mm Japanese", load_type: @rifle)
Caliber.create(name: "303 British", load_type: @rifle)
Caliber.create(name: "7.65 x 53 Mauser", load_type: @rifle)
Caliber.create(name: "32 Winchester Special", load_type: @rifle)
Caliber.create(name: "32-40 Winchester", load_type: @rifle)
Caliber.create(name: "8 x 57mm Mauser", load_type: @rifle)
Caliber.create(name: "325 Winchester Short Magnum", load_type: @rifle)
Caliber.create(name: "8mm Remington Magnum", load_type: @rifle)
Caliber.create(name: "338 Marlin Express", load_type: @rifle)
Caliber.create(name: "338 Federal", load_type: @rifle)
Caliber.create(name: "338-06", load_type: @rifle)
Caliber.create(name: "338 Ruger Compact Magnum", load_type: @rifle)
Caliber.create(name: "338 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "340 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "338 Lapua Magnum", load_type: @rifle)
Caliber.create(name: "338 Remington Ultra Mag", load_type: @rifle)
Caliber.create(name: "338-378 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "348 Winchester", load_type: @rifle)
Caliber.create(name: "357 Magnum", load_type: @rifle)
Caliber.create(name: "35 Remington", load_type: @rifle)
Caliber.create(name: "356 Winchester", load_type: @rifle)
Caliber.create(name: "358 Winchester", load_type: @rifle)
Caliber.create(name: "35 Whelen", load_type: @rifle)
Caliber.create(name: "350 Remington Magnum", load_type: @rifle)
Caliber.create(name: "358 Norma Magnum", load_type: @rifle)
Caliber.create(name: "358 Shooting Times Alaskan", load_type: @rifle)
Caliber.create(name: "9.3 x 62", load_type: @rifle)
Caliber.create(name: "9.3 x 74R", load_type: @rifle)
Caliber.create(name: "38-55 Winchester", load_type: @rifle)
Caliber.create(name: "375 Winchester", load_type: @rifle)
Caliber.create(name: "376 Steyr", load_type: @rifle)
Caliber.create(name: "375 H & H Magnum", load_type: @rifle)
Caliber.create(name: "375 Ruger", load_type: @rifle)
Caliber.create(name: "375 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "375 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "375 Remington Ultra Mag", load_type: @rifle)
Caliber.create(name: "378 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "40-65 Winchester", load_type: @rifle)
Caliber.create(name: "405 Winchester", load_type: @rifle)
Caliber.create(name: "416 Remington Magnum", load_type: @rifle)
Caliber.create(name: "416 Rigby", load_type: @rifle)
Caliber.create(name: "416 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "44-40 Winchester", load_type: @rifle)
Caliber.create(name: "44 Magnum", load_type: @rifle)
Caliber.create(name: "444 Marlin", load_type: @rifle)
Caliber.create(name: "45-70 Government (Trapdoor Rifles)*", load_type: @rifle)
Caliber.create(name: "45-70 Government (Lever Actions)*", load_type: @rifle)
Caliber.create(name: "WWG 457 Mag", load_type: @rifle)
Caliber.create(name: "45-70 Government (Modern Rifles)*", load_type: @rifle)
Caliber.create(name: "450 Marlin", load_type: @rifle)
Caliber.create(name: "45-120 Sharps", load_type: @rifle)
Caliber.create(name: "458 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "460 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "470 Nitro Express", load_type: @rifle)
Caliber.create(name: "50 Alaskan", load_type: @rifle)
Caliber.create(name: "500 CYRUS", load_type: @rifle)
Caliber.create(name: "50-140 Sharps", load_type: @rifle)
Caliber.create(name: "50 Browning Machine Gun", load_type: @rifle)
puts "Finished Caliber data"

# ---------------------------------------------- 
puts "Starting Primer Sizes..."
PrimerSize.create(name: "Small Pistol")
PrimerSize.create(name: "Small Pistol Magnum")
PrimerSize.create(name: "Small Pistol Match")
PrimerSize.create(name: "Small Pistol Magnum Match")
PrimerSize.create(name: "Large Pistol")
PrimerSize.create(name: "Large Pistol Magnum")
PrimerSize.create(name: "Large Pistol Match")
PrimerSize.create(name: "Large Pistol Magnum Match")
PrimerSize.create(name: "Small Rifle")
PrimerSize.create(name: "Small Rifle Magnum")
PrimerSize.create(name: "Small Rifle Match")
PrimerSize.create(name: "Small Rifle Magnum Match")
PrimerSize.create(name: "Small Rifle NATO")
PrimerSize.create(name: "Large Rifle")
PrimerSize.create(name: "Large Rifle Magnum")
PrimerSize.create(name: "Large Rifle Match")
PrimerSize.create(name: "Large Rifle Magnum Match")
PrimerSize.create(name: "Large Rifle NATO")
PrimerSize.create(name: "50 BMG")
PrimerSize.create(name: "410 Shotshell")
PrimerSize.create(name: "12, 16, 20 guage Shotshell")
puts "Finished Primer Sizes"
