# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

puts "Seeding Data..."

# -------------------------------------------------------------------
# 
puts "Starting Manufacturer Data..."
# Manufacturer.create(name: "", abbreviation: "")
Manufacturer.create(name: "Alaska Bullet Company", abbreviation: "AK")
Manufacturer.create(name: "Barnes", abbreviation: "BAR")
Manufacturer.create(name: "Berger", abbreviation: "BRGR")
Manufacturer.create(name: "Berry's", abbreviation: "BRY")
Manufacturer.create(name: "Cast Performance", abbreviation: "CP")
@cci = Manufacturer.create(name: "CCI", abbreviation: "CCI")
@federal = Manufacturer.create(name: "Federal", abbreviation: "FD")
Manufacturer.create(name: "GS Custom Bullets", abbreviation: "GS")
Manufacturer.create(name: "Hornady", abbreviation: "HDY")
Manufacturer.create(name: "Hawk", abbreviation: "HWK")
Manufacturer.create(name: "Laser Cast", abbreviation: "LC")
Manufacturer.create(name: "Lyman", abbreviation: "LYM")
Manufacturer.create(name: "Montana Cast Bullets", abbreviation: "MCB")
Manufacturer.create(name: "Mount Baldy", abbreviation: "MTB")
Manufacturer.create(name: "Montana Gold", abbreviation: "MTG")
Manufacturer.create(name: "Nosler", abbreviation: "NOS")
Manufacturer.create(name: "Oregon Trail", abbreviation: "OT")
Manufacturer.create(name: "Rainier", abbreviation: "RAN")
@remington = Manufacturer.create(name: "Remington", abbreviation: "REM")
Manufacturer.create(name: "Rushmore", abbreviation: "RSH")
@rws = Manufacturer.create(name: "RWS", abbreviation: "RWS")
Manufacturer.create(name: "Sierra", abbreviation: "SIE")
Manufacturer.create(name: "SinterFire", abbreviation: "SF")
Manufacturer.create(name: "Speer", abbreviation: "SPR")
Manufacturer.create(name: "True Shoot", abbreviation: "TS")
Manufacturer.create(name: "West Coast", abbreviation: "WC")
Manufacturer.create(name: "Woodleigh", abbreviation: "WDL")
@winchester = Manufacturer.create(name: "Winchester", abbreviation: "WIN")
puts "Finished Manufacturer data"

# -------------------------------------------------------------------
puts "Starting LoadType data..."
@pistol = LoadType.create(name: "Pistol")
@rifle = LoadType.create(name: "Rifle")
puts "Finished LoadType data"



# -------------------------------------------------------------------
puts "Starting Caliber data..."
puts "... pistol data ..."
Caliber.create(name: "17 Bumble Bee", load_type: @pistol)
Caliber.create(name: "22 Remington Jet", load_type: @pistol)
Caliber.create(name: "22 Hornet", load_type: @pistol)
Caliber.create(name: "22 K Hornet", load_type: @pistol)
Caliber.create(name: "221 Fireball", load_type: @pistol)
Caliber.create(name: "222 Remington", load_type: @pistol)
Caliber.create(name: "223 Remington", load_type: @pistol)
Caliber.create(name: "22 BR Remington", load_type: @pistol)
Caliber.create(name: "6mm TCU", load_type: @pistol)
Caliber.create(name: "6mm-204 RR", load_type: @pistol)
Caliber.create(name: "6mm BR Remington", load_type: @pistol)
Caliber.create(name: "243 Winchester", load_type: @pistol)
Caliber.create(name: "25 ACP", load_type: @pistol)
Caliber.create(name: "25-35 Winchester", load_type: @pistol)
Caliber.create(name: "256 Winchester", load_type: @pistol)
Caliber.create(name: "6.5mm TCU", load_type: @pistol)
Caliber.create(name: "6.5mm BR", load_type: @pistol)
Caliber.create(name: "6.5mm JDJ", load_type: @pistol)
Caliber.create(name: "270 Ren", load_type: @pistol)
Caliber.create(name: "270 Winchester", load_type: @pistol)
Caliber.create(name: "7mm TCU", load_type: @pistol)
Caliber.create(name: "7mm BR Remington", load_type: @pistol)
Caliber.create(name: "7-30 Waters", load_type: @pistol)
Caliber.create(name: "7mm IHMSA", load_type: @pistol)
Caliber.create(name: "7mm-08 Remington", load_type: @pistol)
Caliber.create(name: "30 Luger (7.65mm Parabellum)", load_type: @pistol)
Caliber.create(name: "30 Carbine", load_type: @pistol)
Caliber.create(name: "30 Herrett", load_type: @pistol)
Caliber.create(name: "30-30 Winchester", load_type: @pistol)
Caliber.create(name: "308 Winchester", load_type: @pistol)
Caliber.create(name: "30-06", load_type: @pistol)
Caliber.create(name: "32 ACP", load_type: @pistol)
Caliber.create(name: "32 S&W", load_type: @pistol)
Caliber.create(name: "32 S&W Long", load_type: @pistol)
Caliber.create(name: "32 North American Arms", load_type: @pistol)
Caliber.create(name: "32 H&R Magnum", load_type: @pistol)
Caliber.create(name: "32-20 Winchester", load_type: @pistol)
Caliber.create(name: "327 Federal Magnum", load_type: @pistol)
Caliber.create(name: "380 Auto", load_type: @pistol)
Caliber.create(name: "38 S&W", load_type: @pistol)
Caliber.create(name: "38 Short Colt", load_type: @pistol)
Caliber.create(name: "38 Long Colt", load_type: @pistol)
Caliber.create(name: "9mm Luger", load_type: @pistol)
Caliber.create(name: "38 Super Auto", load_type: @pistol)
Caliber.create(name: "38 Super Auto +P", load_type: @pistol)
Caliber.create(name: "9x23 mm Winchester", load_type: @pistol)
Caliber.create(name: "38 Special", load_type: @pistol)
Caliber.create(name: "38 Special +P", load_type: @pistol)
Caliber.create(name: "357 SIG", load_type: @pistol)
Caliber.create(name: "357 Magnum", load_type: @pistol)
Caliber.create(name: "357-44 Bain & Davis", load_type: @pistol)
Caliber.create(name: "357 Remington Maximum", load_type: @pistol)
Caliber.create(name: "357 Herrett", load_type: @pistol)
Caliber.create(name: "35 Remington", load_type: @pistol)
Caliber.create(name: "9 x 18mm Makarov", load_type: @pistol)
Caliber.create(name: "375 Super Mag", load_type: @pistol)
Caliber.create(name: "375 JDJ", load_type: @pistol)
Caliber.create(name: "38-40 Winchester", load_type: @pistol)
Caliber.create(name: "40 S&W", load_type: @pistol)
Caliber.create(name: "10mm Auto", load_type: @pistol)
Caliber.create(name: "41 Action Express", load_type: @pistol)
Caliber.create(name: "41 Remington Magnum", load_type: @pistol)
Caliber.create(name: "44 Colt", load_type: @pistol)
Caliber.create(name: "44 Russian", load_type: @pistol)
Caliber.create(name: "44 S&W Special", load_type: @pistol)
Caliber.create(name: "44-40 Winchester", load_type: @pistol)
Caliber.create(name: "44 Remington Magnum", load_type: @pistol)
Caliber.create(name: "44 Auto Mag", load_type: @pistol)
Caliber.create(name: "445 Super Mag", load_type: @pistol)
Caliber.create(name: "444 Marlin", load_type: @pistol)
Caliber.create(name: "45 S&W (Schofield)", load_type: @pistol)
Caliber.create(name: "45 GAP (Glock Auto)", load_type: @pistol)
Caliber.create(name: "45 ACP", load_type: @pistol)
Caliber.create(name: "45 SUPER", load_type: @pistol)
Caliber.create(name: "460 Rowland", load_type: @pistol)
Caliber.create(name: "45 Colt", load_type: @pistol)
Caliber.create(name: "45 Colt (Ruger, Freedom Arms & T/C only)", load_type: @pistol)
Caliber.create(name: "45 Winchester Magnum", load_type: @pistol)
Caliber.create(name: "450 Extreme", load_type: @pistol)
Caliber.create(name: "454 Casull", load_type: @pistol)
Caliber.create(name: "460 S&W MAGNUM", load_type: @pistol)
Caliber.create(name: "45-70 Government", load_type: @pistol)
Caliber.create(name: "480 Ruger", load_type: @pistol)
Caliber.create(name: "475 Linebaugh", load_type: @pistol)
Caliber.create(name: "50 Action Express", load_type: @pistol)
Caliber.create(name: "500 Linebaugh", load_type: @pistol)
Caliber.create(name: "500 Wyoming Express", load_type: @pistol)
Caliber.create(name: "500 S&W Magnum", load_type: @pistol)
puts "... loading rifle data ..."
Caliber.create(name: "17 Ackley Hornet", load_type: @rifle)
Caliber.create(name: "17 Ackley Bee", load_type: @rifle)
Caliber.create(name: "17 Mach IV", load_type: @rifle)
Caliber.create(name: "17 Remington Fireball", load_type: @rifle)
Caliber.create(name: "17-222", load_type: @rifle)
Caliber.create(name: "17-223", load_type: @rifle)
Caliber.create(name: "17 Remington", load_type: @rifle)
Caliber.create(name: "20 Tactical", load_type: @rifle)
Caliber.create(name: "204 Ruger", load_type: @rifle)
Caliber.create(name: "22 Hornet", load_type: @rifle)
Caliber.create(name: "22 K Hornet", load_type: @rifle)
Caliber.create(name: "218 Bee", load_type: @rifle)
Caliber.create(name: "221 Fireball", load_type: @rifle)
Caliber.create(name: "222 Remington", load_type: @rifle)
Caliber.create(name: "223 Remington", load_type: @rifle)
Caliber.create(name: "222 Remington Magnum", load_type: @rifle)
Caliber.create(name: "22 PPC", load_type: @rifle)
Caliber.create(name: "22 BR Remington", load_type: @rifle)
Caliber.create(name: "224 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "219 Wasp", load_type: @rifle)
Caliber.create(name: "225 Winchester", load_type: @rifle)
Caliber.create(name: "22-250 Remington", load_type: @rifle)
Caliber.create(name: "220 Swift", load_type: @rifle)
Caliber.create(name: "220 Jaybird", load_type: @rifle)
Caliber.create(name: "22 CHeetah Mark II", load_type: @rifle)
Caliber.create(name: "223 Winchester Super Short Magnum", load_type: @rifle)
Caliber.create(name: "6mm-222", load_type: @rifle)
Caliber.create(name: "6 x 45mm (6mm-223)", load_type: @rifle)
Caliber.create(name: "6 x 47mm", load_type: @rifle)
Caliber.create(name: "6mm PPC", load_type: @rifle)
Caliber.create(name: "6mm BR Remington", load_type: @rifle)
Caliber.create(name: "6mm-250", load_type: @rifle)
Caliber.create(name: "243 Winchester", load_type: @rifle)
Caliber.create(name: "6mm Remington", load_type: @rifle)
Caliber.create(name: "243 Winchester Super Short Magnum", load_type: @rifle)
Caliber.create(name: "6mm - 284", load_type: @rifle)
Caliber.create(name: "240 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "25-20 Winchester", load_type: @rifle)
Caliber.create(name: "256 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "25-35 Winchester", load_type: @rifle)
Caliber.create(name: "257 Kimber", load_type: @rifle)
Caliber.create(name: "250-3000 Savage", load_type: @rifle)
Caliber.create(name: "257 Roberts", load_type: @rifle)
Caliber.create(name: "25-284", load_type: @rifle)
Caliber.create(name: "25-06 Remington", load_type: @rifle)
Caliber.create(name: "25 Winchester Super Short Magnum", load_type: @rifle)
Caliber.create(name: "257 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "6.5mm Grendel", load_type: @rifle)
Caliber.create(name: "6.5mm BR", load_type: @rifle)
Caliber.create(name: "6.5 x 50mm Japanese", load_type: @rifle)
Caliber.create(name: "6.5mm Carcano", load_type: @rifle)
Caliber.create(name: "6.5 Creedmoor", load_type: @rifle)
Caliber.create(name: "260 Remington", load_type: @rifle)
Caliber.create(name: "6.5 x 55mm Swedish Mauser", load_type: @rifle)
Caliber.create(name: "6.5mm-06", load_type: @rifle)
Caliber.create(name: "6.5-284", load_type: @rifle)
Caliber.create(name: "6.5mm Remington Magnum", load_type: @rifle)
Caliber.create(name: "264 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "6.8 mm Remington SPC", load_type: @rifle)
Caliber.create(name: "270 Winchester", load_type: @rifle)
Caliber.create(name: "270 Winchester Short Magnum", load_type: @rifle)
Caliber.create(name: "270 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "7mm BR Remington", load_type: @rifle)
Caliber.create(name: "7-30 Waters", load_type: @rifle)
Caliber.create(name: "7mm-08 Remington", load_type: @rifle)
Caliber.create(name: "7mm Shooting Times Easterner", load_type: @rifle)
Caliber.create(name: "7 x 57mm Mauser", load_type: @rifle)
Caliber.create(name: "280 Remington", load_type: @rifle)
Caliber.create(name: "284 Winchester", load_type: @rifle)
Caliber.create(name: "280 Ackley Improved", load_type: @rifle)
Caliber.create(name: "7mm Rem. S.A. Ultra Mag.", load_type: @rifle)
Caliber.create(name: "7mm Winchester Short Magnum", load_type: @rifle)
Caliber.create(name: "7mm Remington Magnum", load_type: @rifle)
Caliber.create(name: "7mm Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "7mm Shooting Times Westerner", load_type: @rifle)
Caliber.create(name: "7mm Remington Ultra Magnum", load_type: @rifle)
Caliber.create(name: "30 Carbine", load_type: @rifle)
Caliber.create(name: "300 AAC Blackout", load_type: @rifle)
Caliber.create(name: "30-30 Winchester", load_type: @rifle)
Caliber.create(name: "30 AR Remington", load_type: @rifle)
Caliber.create(name: "30-40 Krag", load_type: @rifle)
Caliber.create(name: "7.5 x 55mm Swiss", load_type: @rifle)
Caliber.create(name: "300 Savage", load_type: @rifle)
Caliber.create(name: "7.62 x 54R", load_type: @rifle)
Caliber.create(name: "30 Remington", load_type: @rifle)
Caliber.create(name: "307 Winchester", load_type: @rifle)
Caliber.create(name: "308 Marlin Express", load_type: @rifle)
Caliber.create(name: "30 TC", load_type: @rifle)
Caliber.create(name: "308 Winchester", load_type: @rifle)
Caliber.create(name: "30-06", load_type: @rifle)
Caliber.create(name: "300 H & H Magnum", load_type: @rifle)
Caliber.create(name: "308 Norma Magnum", load_type: @rifle)
Caliber.create(name: "300 Ruger Compact Magnum", load_type: @rifle)
Caliber.create(name: "300 Remington S.A. Ultra Mag.", load_type: @rifle)
Caliber.create(name: "300 Winchester Short Magnum", load_type: @rifle)
Caliber.create(name: "300 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "300 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "300 Remington Ultra Mag", load_type: @rifle)
Caliber.create(name: "30-378 Weatherby", load_type: @rifle)
Caliber.create(name: "7.62 x 39mm Russian", load_type: @rifle)
Caliber.create(name: "303 Savage", load_type: @rifle)
Caliber.create(name: "7.7 x 58mm Japanese", load_type: @rifle)
Caliber.create(name: "303 British", load_type: @rifle)
Caliber.create(name: "7.65 x 53 Mauser", load_type: @rifle)
Caliber.create(name: "32 Winchester Special", load_type: @rifle)
Caliber.create(name: "32-40 Winchester", load_type: @rifle)
Caliber.create(name: "8 x 57mm Mauser", load_type: @rifle)
Caliber.create(name: "325 Winchester Short Magnum", load_type: @rifle)
Caliber.create(name: "8mm Remington Magnum", load_type: @rifle)
Caliber.create(name: "338 Marlin Express", load_type: @rifle)
Caliber.create(name: "338 Federal", load_type: @rifle)
Caliber.create(name: "338-06", load_type: @rifle)
Caliber.create(name: "338 Ruger Compact Magnum", load_type: @rifle)
Caliber.create(name: "338 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "340 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "338 Lapua Magnum", load_type: @rifle)
Caliber.create(name: "338 Remington Ultra Mag", load_type: @rifle)
Caliber.create(name: "338-378 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "348 Winchester", load_type: @rifle)
Caliber.create(name: "357 Magnum", load_type: @rifle)
Caliber.create(name: "35 Remington", load_type: @rifle)
Caliber.create(name: "356 Winchester", load_type: @rifle)
Caliber.create(name: "358 Winchester", load_type: @rifle)
Caliber.create(name: "35 Whelen", load_type: @rifle)
Caliber.create(name: "350 Remington Magnum", load_type: @rifle)
Caliber.create(name: "358 Norma Magnum", load_type: @rifle)
Caliber.create(name: "358 Shooting Times Alaskan", load_type: @rifle)
Caliber.create(name: "9.3 x 62", load_type: @rifle)
Caliber.create(name: "9.3 x 74R", load_type: @rifle)
Caliber.create(name: "38-55 Winchester", load_type: @rifle)
Caliber.create(name: "375 Winchester", load_type: @rifle)
Caliber.create(name: "376 Steyr", load_type: @rifle)
Caliber.create(name: "375 H & H Magnum", load_type: @rifle)
Caliber.create(name: "375 Ruger", load_type: @rifle)
Caliber.create(name: "375 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "375 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "375 Remington Ultra Mag", load_type: @rifle)
Caliber.create(name: "378 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "40-65 Winchester", load_type: @rifle)
Caliber.create(name: "405 Winchester", load_type: @rifle)
Caliber.create(name: "416 Remington Magnum", load_type: @rifle)
Caliber.create(name: "416 Rigby", load_type: @rifle)
Caliber.create(name: "416 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "44-40 Winchester", load_type: @rifle)
Caliber.create(name: "44 Magnum", load_type: @rifle)
Caliber.create(name: "444 Marlin", load_type: @rifle)
Caliber.create(name: "45-70 Government (Trapdoor Rifles)*", load_type: @rifle)
Caliber.create(name: "45-70 Government (Lever Actions)*", load_type: @rifle)
Caliber.create(name: "WWG 457 Mag", load_type: @rifle)
Caliber.create(name: "45-70 Government (Modern Rifles)*", load_type: @rifle)
Caliber.create(name: "450 Marlin", load_type: @rifle)
Caliber.create(name: "45-120 Sharps", load_type: @rifle)
Caliber.create(name: "458 Winchester Magnum", load_type: @rifle)
Caliber.create(name: "460 Weatherby Magnum", load_type: @rifle)
Caliber.create(name: "470 Nitro Express", load_type: @rifle)
Caliber.create(name: "50 Alaskan", load_type: @rifle)
Caliber.create(name: "500 CYRUS", load_type: @rifle)
Caliber.create(name: "50-140 Sharps", load_type: @rifle)
Caliber.create(name: "50 Browning Machine Gun", load_type: @rifle)
puts "Finished Caliber data"

# ---------------------------------------------- 
puts "Starting Primer Sizes..."
@sp = PrimerSize.create(name: "Small Pistol")
@spmag = PrimerSize.create(name: "Small Pistol Magnum")
@spm = PrimerSize.create(name: "Small Pistol Match")
@spmm = PrimerSize.create(name: "Small Pistol Magnum Match")
@lp = PrimerSize.create(name: "Large Pistol")
@lpmag = PrimerSize.create(name: "Large Pistol Magnum")
@lpm = PrimerSize.create(name: "Large Pistol Match")
@lpmm = PrimerSize.create(name: "Large Pistol Magnum Match")
@sr = PrimerSize.create(name: "Small Rifle")
@srmag = PrimerSize.create(name: "Small Rifle Magnum")
@srm = PrimerSize.create(name: "Small Rifle Match")
@srmm = PrimerSize.create(name: "Small Rifle Magnum Match")
@srnato = PrimerSize.create(name: "Small Rifle NATO")
@lr = PrimerSize.create(name: "Large Rifle")
@lrmag = PrimerSize.create(name: "Large Rifle Magnum")
@lrm = PrimerSize.create(name: "Large Rifle Match")
@lrmm = PrimerSize.create(name: "Large Rifle Magnum Match")
@lrnato = PrimerSize.create(name: "Large Rifle NATO")
@bmg = PrimerSize.create(name: "50 BMG")
@shot410 = PrimerSize.create(name: "410 Shotshell")
@shotshell = PrimerSize.create(name: "12, 16, 20 guage Shotshell")
puts "Finished Primer Sizes"
puts ""
# -----------------------------------
puts "Starting Primers..."
Primer.create(name: "500", manufacturer: @cci, primer_size: @sp)
Primer.create(name: "550", manufacturer: @cci, primer_size: @spmag)
Primer.create(name: "300", manufacturer: @cci, primer_size: @lp)
Primer.create(name: "350", manufacturer: @cci, primer_size: @lpmag)
Primer.create(name: "400", manufacturer: @cci, primer_size: @sr)
Primer.create(name: "450", manufacturer: @cci, primer_size: @srmag)
Primer.create(name: "BR4", manufacturer: @cci, primer_size: @srm)
Primer.create(name: "#41", manufacturer: @cci, primer_size: @srnato)
Primer.create(name: "200", manufacturer: @cci, primer_size: @lr)
Primer.create(name: "250", manufacturer: @cci, primer_size: @lrmag)
Primer.create(name: "BR2", manufacturer: @cci, primer_size: @lrm)
Primer.create(name: "#34", manufacturer: @cci, primer_size: @lrnato)
Primer.create(name: "#35", manufacturer: @cci, primer_size: @bmg)
Primer.create(name: "209, 209M", manufacturer: @cci, primer_size: @shot410)
Primer.create(name: "209, 209M", manufacturer: @cci, primer_size: @shotshell)

Primer.create(name: "100", manufacturer: @federal, primer_size: @sp)
Primer.create(name: "200", manufacturer: @federal, primer_size: @spmag)
Primer.create(name: "100M", manufacturer: @federal, primer_size: @spm)
Primer.create(name: "200M", manufacturer: @federal, primer_size: @spmm)
Primer.create(name: "150", manufacturer: @federal, primer_size: @lp)
Primer.create(name: "155", manufacturer: @federal, primer_size: @lpmag)
Primer.create(name: "150M", manufacturer: @federal, primer_size: @lpm)
Primer.create(name: "155M", manufacturer: @federal, primer_size: @lpmm)
Primer.create(name: "205", manufacturer: @federal, primer_size: @sr)
Primer.create(name: "205M", manufacturer: @federal, primer_size: @srm)
Primer.create(name: "210", manufacturer: @federal, primer_size: @lr)
Primer.create(name: "215", manufacturer: @federal, primer_size: @lrmag)
Primer.create(name: "210M", manufacturer: @federal, primer_size: @lrm)
Primer.create(name: "215M", manufacturer: @federal, primer_size: @lrmm)
Primer.create(name: "209", manufacturer: @federal, primer_size: @shot410)
Primer.create(name: "209", manufacturer: @federal, primer_size: @shotshell)

Primer.create(name: "1.5", manufacturer: @remington, primer_size: @sp)
Primer.create(name: "5.5", manufacturer: @remington, primer_size: @spmag)
Primer.create(name: "2.5", manufacturer: @remington, primer_size: @lp)
Primer.create(name: "6.5", manufacturer: @remington, primer_size: @sr)
Primer.create(name: "7.5", manufacturer: @remington, primer_size: @srmag)
Primer.create(name: "9.5", manufacturer: @remington, primer_size: @lr)
Primer.create(name: "9.5M", manufacturer: @remington, primer_size: @lrmag)
Primer.create(name: "410", manufacturer: @remington, primer_size: @shot410)
Primer.create(name: "209", manufacturer: @remington, primer_size: @shotshell)

Primer.create(name: "4031", manufacturer: @rws, primer_size: @sp)
Primer.create(name: "4047", manufacturer: @rws, primer_size: @spmag)
Primer.create(name: "5337", manufacturer: @rws, primer_size: @lp)
Primer.create(name: "4033", manufacturer: @rws, primer_size: @sr)
Primer.create(name: "5341", manufacturer: @rws, primer_size: @lr)
Primer.create(name: "5333", manufacturer: @rws, primer_size: @lrmag)

Primer.create(name: "WSP", manufacturer: @winchester, primer_size: @sp)
Primer.create(name: "WSPM", manufacturer: @winchester, primer_size: @spmag)
Primer.create(name: "WLP", manufacturer: @winchester, primer_size: @lp)
Primer.create(name: "WSR", manufacturer: @winchester, primer_size: @sr)
Primer.create(name: "WLR", manufacturer: @winchester, primer_size: @lr)
Primer.create(name: "WLRM", manufacturer: @winchester, primer_size: @lrmag)
Primer.create(name: "8312", manufacturer: @winchester, primer_size: @shot410)
Primer.create(name: "W209", manufacturer: @winchester, primer_size: @shotshell)

puts "Finished Primers"
puts ""

puts "Starting BulletTypes..."
BulletType.create(acronym: "", name: "")
BulletType.create(acronym: "AP", name: "Armor Piercing")
BulletType.create(acronym: "API", name: "Aromor Piercing Incendiary")
BulletType.create(acronym: "BBWC", name: "Bevel Base Wadcutter")
BulletType.create(acronym: "BEB", name: "Brass Enclosed Bass")
BulletType.create(acronym: "BJHP", name: "Brass Jacketed Hollow Point")
BulletType.create(acronym: "BST", name: "Ballistic Silvertip")
BulletType.create(acronym: "BT", name: "Boat Tail")
BulletType.create(acronym: "BTHP", name: "Boat Tail Hollow Point")
BulletType.create(acronym: "BTSP", name: "Boat Tail Soft Point")
BulletType.create(acronym: "BRPT", name: "Bronze Point")
BulletType.create(acronym: "CC", name: "Copper Coated")
BulletType.create(acronym: "CP", name: "Copper Plated")
BulletType.create(acronym: "CL", name: "Core-Lokt")
BulletType.create(acronym: "ENCAP", name: "Encapsulated")
BulletType.create(acronym: "EFMJ", name: "Expanding Full Metal Jacket")
BulletType.create(acronym: "EP", name: "Expanding Point")
BulletType.create(acronym: "ERBT", name: "Extended-Range Boat Tail")
BulletType.create(acronym: "FMC", name: "Full Metal Case")
BulletType.create(acronym: "FMJ", name: "Full Metal Jacket")
BulletType.create(acronym: "FMJBT", name: "Full Metal Jacket Boat-Tail")
BulletType.create(acronym: "FMJE", name: "Full Metal Jacket Encapsulated")
BulletType.create(acronym: "FPJ", name: "Flat Point Jacketed")
BulletType.create(acronym: "FPPN", name: "Flat Point Penetrator")
BulletType.create(acronym: "FNSP", name: "Flast Nose Soft Point")
BulletType.create(acronym: "FRAN", name: "Frangible")
BulletType.create(acronym: "GCK", name: "Gas Check")
BulletType.create(acronym: "GDHP", name: "Gold Dot Hollow Point")
BulletType.create(acronym: "GS", name: "Grand Slam")
BulletType.create(acronym: "HBWC", name: "Hollow Base Wadcutter")
BulletType.create(acronym: "HSHK", name: "Hydra-Shok")
BulletType.create(acronym: "HP", name: "Hollow Point")
BulletType.create(acronym: "HPBT", name: "Hollow Point Boat-Tail")
BulletType.create(acronym: "HSP", name: "Hollow Soft Point")
BulletType.create(acronym: "HV", name: "High Velocity")
BulletType.create(acronym: "JFP", name: "Jacketed Flat Point")
BulletType.create(acronym: "JHC", name: "Jacketed Hollow Cavity")
BulletType.create(acronym: "JHP", name: "Jacketed Hollow Point")
BulletType.create(acronym: "JSP", name: "Jacketd Soft Point")
BulletType.create(acronym: "L", name: "Lead")
BulletType.create(acronym: "LRN", name: "Lead Round Nose")
BulletType.create(acronym: "LSWC", name: "Lead Semi-Wadcutter")
BulletType.create(acronym: "LSWCHP", name: "Lead Semi-Wadcutter Hollow Point")
BulletType.create(acronym: "MB", name: "Multi-ball")
BulletType.create(acronym: "MC", name: "Metal Case")
BulletType.create(acronym: "MCH", name: "MCH")
BulletType.create(acronym: "MK", name: "MatchKing")
BulletType.create(acronym: "MOLY", name: "Moly-Coated")
BulletType.create(acronym: "NBT", name: "Nosler Ballistic Tip")
BulletType.create(acronym: "NP", name: "Nosler Partition")
BulletType.create(acronym: "PEP", name: "Positive Expanding Point")
BulletType.create(acronym: "PG", name: "Partition Gold")
BulletType.create(acronym: "PL", name: "Power-Lokt")
BulletType.create(acronym: "PP", name: "Power-Point")
BulletType.create(acronym: "PSP", name: "Pointed Soft Point")
BulletType.create(acronym: "PTHP", name: "Platinum-Tipped Hollow Point")
BulletType.create(acronym: "PWC", name: "Pointed Wadcutter")
BulletType.create(acronym: "RN", name: "Round Nose")
BulletType.create(acronym: "SBK", name: "Sierra BlitzKing")
BulletType.create(acronym: "SFS", name: "Supreme Fail Safe")
BulletType.create(acronym: "SJHP", name: "Semi-Jacketed Hollow Point")
BulletType.create(acronym: "SJSP", name: "Semi-Jacketed Soft Point")
BulletType.create(acronym: "SLD", name: "Solid")
BulletType.create(acronym: "SMP", name: "Semi-Pointed")
BulletType.create(acronym: "SP", name: "Soft Point")
BulletType.create(acronym: "SPCE", name: "Soft Point Cutting Edge")
BulletType.create(acronym: "SPCL", name: "Soft Point Core-Lokt")
BulletType.create(acronym: "SPT", name: "Spitzer")
BulletType.create(acronym: "SST", name: "Super Shock Tipped")
BulletType.create(acronym: "ST", name: "Silvertip")
BulletType.create(acronym: "STHP", name: "Silvertip Hollow Point")
BulletType.create(acronym: "SWC", name: "Semi-Wadcutter")
BulletType.create(acronym: "SXT", name: "Supreme Expansion Technology")
BulletType.create(acronym: "TAP", name: "Tactical Application Police")
BulletType.create(acronym: "TC", name: "Truncated Cone")
BulletType.create(acronym: "TCHP", name: "Truncated Cone Hollow Point")
BulletType.create(acronym: "TCSB", name: "Truncated Cone Solid Bullet")
BulletType.create(acronym: "TMJ", name: "Total Metal Jacket")
BulletType.create(acronym: "TMWC", name: "Target-Master Wadcutter")
BulletType.create(acronym: "V-Max", name: "Varmint Express Ballistic Tip")
BulletType.create(acronym: "XTP", name: "Extreme Terminal Performance")




puts "Finished BulletTypes."
